# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2022-03-11 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
                ('deadline', models.DateField()),
                ('schoolClass', models.CharField(choices=[('deutsch', 'DEUSCH'), ('mathe', 'MATHE'), ('englisch', 'ENGLISCH'), ('französisch', 'FRANZÖSISCH'), ('chemie', 'CHEMIE'), ('physik', 'PHYSIK'), ('biologie', 'BIOLOGIE'), ('informatik', 'INFORMATIK'), ('geschichte', 'GESCHICHTE'), ('musik', 'MUSIK'), ('religion', 'RELIGION'), ('kunst', 'KUNST')], default='deutsch', max_length=12)),
                ('done', models.BooleanField(default=False, editable=False)),
                ('username', models.UUIDField(editable=False)),
            ],
        ),
    ]
